export let imoveis = [
    {
        estado:'PB',
    cidade:'João Pessoa',
    bairro:'Água fria',
    rua:'da água',
    numero:'123',
    cep:'987456321',
    quartos:'3',
    Banheiros:'2',
    garagem:'2',
    capacidade:'6',
    descricao:'poiuytrewqasdfghjkl,mnbvcxz',
    },
    {
        estado:'PE',
    cidade:'Timbaúba',
    bairro:'Centro',
    rua:'Marechal',
    numero:'65',
    cep:'55879600',
    quartos:'2',
    Banheiros:'1',
    garagem:'1',
    capacidade:'4',
    descricao:'poiuyhjkloiuytrewsdfghjkmnbvcxzasxza',
    },
    {
        estado:'CE',
    cidade:'Tiai',
    bairro:'Cerejeira',
    rua:'sergio muniz',
    numero:'56',
    cep:'32146963',
    quartos:'1',
    Banheiros:'1',
    garagem:'1',
    capacidade:'5',
    descricao:'poiuytrewqasdfghjklmnbvcxsdfghjkoiuytrew',
    }
]